import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

// Load fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata (used by Next.js)
export const metadata = {
  title: "Awesome Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased min-h-screen flex flex-col">
        {/* Navbar */}
        <Navbar></Navbar>

        {/* Main Content */}
        <main className="flex-1 min-h-[calc(100vh-7rem)] place-content-center text-center">
          {children}
        </main>

        {/* Footer */}
        <Footer></Footer>
      </body>
    </html>
  );
}
